name: Upload cloudfree
on:
  push:
    branches:
      - main
  # Actions タブから手動でワークフローを実行できるようにします
  workflow_dispatch:

jobs:
  deploy:
    name: FTP upload to cloudfree
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          version: ^10.17.0
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm vite build
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          local-dir: ./dist/
